[package]
name = "language_learner"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-openai = "0.17.1"
tokio = { version = "1", features = ["full"] }
csv = "1.3.0"
